# Generated by Django 4.2.14 on 2024-10-03 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Child',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Фамилия', models.CharField(max_length=30)),
                ('Имя', models.CharField(max_length=30)),
                ('Отчество', models.CharField(max_length=30)),
                ('Возраст', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Фамилия', models.CharField(max_length=30)),
                ('Имя', models.CharField(max_length=30)),
                ('Отчество', models.CharField(max_length=30)),
                ('Опыт работы', models.IntegerField()),
                ('должность', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Название', models.CharField(max_length=50)),
                ('Цена', models.IntegerField()),
                ('Время проведения', models.TimeField()),
                ('childs', models.ManyToManyField(related_name='services', to='lion.child')),
                ('teachers', models.ManyToManyField(related_name='services', to='lion.teacher')),
            ],
        ),
        migrations.AddField(
            model_name='child',
            name='teachers',
            field=models.ManyToManyField(related_name='childs', to='lion.teacher'),
        ),
    ]
