# Generated by Django 4.2.14 on 2024-10-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='child',
            name='Возраст',
        ),
        migrations.RemoveField(
            model_name='child',
            name='Имя',
        ),
        migrations.RemoveField(
            model_name='child',
            name='Отчество',
        ),
        migrations.RemoveField(
            model_name='child',
            name='Фамилия',
        ),
        migrations.RemoveField(
            model_name='service',
            name='Время проведения',
        ),
        migrations.RemoveField(
            model_name='service',
            name='Название',
        ),
        migrations.RemoveField(
            model_name='service',
            name='Цена',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Имя',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Опыт работы',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Отчество',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='Фамилия',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='должность',
        ),
        migrations.AddField(
            model_name='child',
            name='age',
            field=models.IntegerField(default=1, null=True, verbose_name='Возраст'),
        ),
        migrations.AddField(
            model_name='child',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='child',
            name='last_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='child',
            name='surname',
            field=models.CharField(max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='service',
            name='during_time',
            field=models.TimeField(null=True, verbose_name='Время проведения'),
        ),
        migrations.AddField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=50, null=True, verbose_name='Название'),
        ),
        migrations.AddField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Цена'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='first_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Имя'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='last_name',
            field=models.CharField(max_length=30, null=True, verbose_name='Отчество'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='surname',
            field=models.CharField(max_length=30, null=True, verbose_name='Фамилия'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_experience',
            field=models.IntegerField(null=True, verbose_name='Опыт работы'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='work_position',
            field=models.CharField(max_length=30, null=True, verbose_name='Должность'),
        ),
    ]
