# Generated by Django 4.2.14 on 2024-10-03 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lion', '0003_alter_child_age_alter_child_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChildClub',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название кружка')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена')),
                ('teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='clubs', to='lion.teacher')),
            ],
        ),
        migrations.RemoveField(
            model_name='child',
            name='teachers',
        ),
        migrations.DeleteModel(
            name='Service',
        ),
        migrations.AddField(
            model_name='childclub',
            name='child',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lion.child'),
        ),
        migrations.AddField(
            model_name='childclub',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lion.club'),
        ),
        migrations.AlterUniqueTogether(
            name='childclub',
            unique_together={('child', 'club')},
        ),
    ]
