# Generated by Django 4.2.14 on 2024-10-03 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lion', '0004_childclub_club_remove_child_teachers_delete_service_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='childclub',
            name='teacher',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lion.teacher'),
            preserve_default=False,
        ),
    ]
