# Generated by Django 4.2.14 on 2024-10-03 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lion', '0006_alter_childclub_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='club',
            name='teacher',
        ),
    ]
